### ISSUE TITLE
Come up with rule file

### ISSUE THREAD

**Issue by the-c0d3br34k3r** [padaiyal/sanitizer#2]
```
name:
description:
format: <json|xml|txt>
rules:
    <JSONPath|XPath|Regex>:
            description:
            action: <contextual_replace|remove>
```

https://skarlso.github.io/2023/12/01/crd-to-yaml-as-wasm-website/
